//
// Created by Dan on 4/3/2016.
//

#ifndef PARTIALORDERPLANNER_ATTRIBUTE_H
#define PARTIALORDERPLANNER_ATTRIBUTE_H

enum Attribute
{
    AGGRESSION,
    CHARM,
    INTELLIGENCE,
    NumberOfAttributes
};

#endif //PARTIALORDERPLANNER_ATTRIBUTE_H
